-- Création des tables de base si elles n'existent pas
create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null,
  description text,
  image_url text,
  created_at timestamptz not null default now()
);

-- Ajout de la colonne image_url si elle n'existe pas déjà
alter table public.products 
add column if not exists image_url text;

-- Création du bucket pour les images de produits
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 
  'product-images', 
  true, 
  5242880, -- 5MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
) on conflict (id) do nothing;

-- Politiques RLS pour le bucket product-images
create policy "Anyone can view product images" on storage.objects
for select using (bucket_id = 'product-images');

create policy "Restaurant owners can upload product images" on storage.objects
for insert with check (
  bucket_id = 'product-images' and 
  auth.role() = 'authenticated'
);

create policy "Restaurant owners can update product images" on storage.objects
for update using (
  bucket_id = 'product-images' and 
  auth.role() = 'authenticated'
);

create policy "Restaurant owners can delete their product images" on storage.objects
for delete using (
  bucket_id = 'product-images' and 
  auth.role() = 'authenticated'
);
