-- Création de la table des types de cuisine
create table if not exists public.cuisine_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text, -- emoji ou icône
  color text default '#emerald-500',
  created_at timestamptz not null default now()
);

-- Table de liaison entre restaurants et types de cuisine (many-to-many)
create table if not exists public.restaurant_cuisine_types (
  restaurant_id bigint references public.restaurants(id) on delete cascade,
  cuisine_type_id bigint references public.cuisine_types(id) on delete cascade,
  primary key (restaurant_id, cuisine_type_id)
);

-- Insertion des types de cuisine courants
insert into public.cuisine_types (name, icon, color) values
('Italienne', '🍝', '#red-500'),
('Japonaise', '🍱', '#pink-500'),
('Chinoise', '🥡', '#orange-500'),
('Française', '🥐', '#blue-500'),
('Belge', '🍟', '#yellow-500'),
('Mexicaine', '🌮', '#green-500'),
('Indienne', '🍛', '#purple-500'),
('Thaïlandaise', '🍜', '#red-600'),
('Vietnamienne', '🍲', '#orange-600'),
('Américaine', '🍔', '#blue-600'),
('Burger', '🍔', '#amber-500'),
('Pizza', '🍕', '#red-500'),
('Sushi', '🍣', '#pink-500'),
('Végétarienne', '🥗', '#green-600'),
('Végane', '🌱', '#green-700'),
('Healthy', '🥗', '#emerald-500'),
('Fast Food', '🍟', '#yellow-500'),
('Gastronomique', '🍽️', '#purple-600'),
('Bio', '🌿', '#green-500'),
('Sans Gluten', '🌾', '#amber-600'),
('Pâtisserie', '🧁', '#pink-500'),
('Café', '☕', '#brown-500'),
('Bar', '🍺', '#indigo-500'),
('Brunch', '🍳', '#orange-500')
on conflict (name) do nothing;

-- Activation du RLS
alter table public.cuisine_types enable row level security;
alter table public.restaurant_cuisine_types enable row level security;

-- Politiques pour les types de cuisine (lecture publique)
create policy "Cuisine types are public readable" on public.cuisine_types
for select using (true);

-- Politiques pour les liaisons restaurant-cuisine (gérées par le propriétaire)
create policy "Restaurant cuisine types are manageable by restaurant owner" on public.restaurant_cuisine_types
for all using (
  restaurant_id in (
    select id from public.restaurants where owner_id = auth.uid()
  )
)
with check (
  restaurant_id in (
    select id from public.restaurants where owner_id = auth.uid()
  )
);
